export const items = [
	{
		id: 1,
		img: '/abbumayabimahim.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},

	{
		id: 2,
		img: '/amimayabimahim3.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},

	{
		id: 3,
		img: '/amramahim3.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 4,
		img: '/amramahimgolf.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 5,
		img: '/amramahim.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},

	{
		id: 6,
		img: '/amramayabi2.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 7,
		img: '/mayabiamrabd2.png',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},

	{
		id: 8,
		img: '/mayabiabbu.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},

	{
		id: 9,
		img: '/mahimabbuyel2.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 10,
		img: '/mahimabbu2.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 11,
		img: '/mahimbabadub.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},

	{
		id: 12,
		img: '/mayabiami2.PNG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},

	{
		id: 13,
		img: '/mahimami3.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 14,
		img: '/blackfs.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 15,
		img: '/mahimabbu7.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 16,
		img: '/amimahimbd.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 17,
		img: '/amramahimblac.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 18,
		img: '/family2.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 19,
		img: '/mahimabbu3.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 20,
		img: '/mahimbaba15.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 21,
		img: '/mahimbabaubc.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 22,
		img: '/bhaibon1.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 23,
		img: '/bhaibon2.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 24,
		img: '/bhaibon3.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 25,
		img: '/bhaibon5.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 26,
		img: '/bhibon4.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 27,
		img: '/amra21.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 28,
		img: '/amratt.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 29,
		img: '/sonyamra.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 30,
		img: '/mayabiabbu23.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 31,
		img: '/mayabiabbu21.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 32,
		img: '/amimayabimahim21.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 33,
		img: '/bhibon21.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 34,
		img: '/babamahimayabi.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 35,
		img: '/bhaibon15.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 36,
		img: '/amimayabi20.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 37,
		img: '/amrafamily2.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 38,
		img: '/amimayabiwhite.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 39,
		img: '/bhaibon13.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 40,
		img: '/abbumayabimahim21.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 41,
		img: '/amramahim9.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 42,
		img: '/amramayabi31.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 43,
		img: '/amramahim8.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 44,
		img: '/bhaibon25.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 45,
		img: '/amimayabigrad1.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 46,
		img: '/babamayabigrad.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 47,
		img: '/family5.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 48,
		img: '/amimayabi27.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 49,
		img: '/amimayabimahimgrad.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 50,
		img: '/amimayabigrad.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 51,
		img: '/amramayabidrad.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 52,
		img: '/amimayabi12.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 53,
		img: '/amimahim19.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 54,
		img: '/bhaibon24.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, influence families and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 55,
		img: '/amramayabi30.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 56,
		img: '/amimayabi26.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 57,
		img: '/bhaibon23.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 58,
		img: '/amradoel.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 59,
		img: '/amimayabi18.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 60,
		img: '/amra23.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 61,
		img: '/babamahimmayabi.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 62,
		img: '/bhaibon16.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 63,
		img: '/amimayabimahim11.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 64,
		img: '/family6.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 65,
		img: '/bhaibon24.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 66,
		img: '/amimayabi28.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 67,
		img: '/amimayabi27.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 69,
		img: '/amimayabimahim.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 70,
		img: '/bhaibon25.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 71,
		img: '/bhaibon23.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 72,
		img: '/bhaibon33.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 73,
		img: '/babamahidubai.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 74,
		img: '/amimahimdubai.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 75,
		img: '/amrathai3.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 76,
		img: '/amimahim16.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 77,
		img: '/bhaibon20.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 78,
		img: '/bhaibon18.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 79,
		img: '/bhaibon17.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 80,
		img: '/amramayabitteid.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 81,
		img: '/amimayabilahenga.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},

	{
		id: 83,
		img: '/amramahim4.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 84,
		img: '/amrablue.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 85,
		img: '/amraraima1.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 86,
		img: '/amra1.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 87,
		img: '/amrablack.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 88,
		img: '/amimayabi12.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 89,
		img: '/amimahim16.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 90,
		img: '/family8.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 91,
		img: '/familyk.JPG',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 92,
		img: '/familyjamdani1.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},

	{
		id: 93,
		img: '/amimayabiu3.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 94,
		img: '/babamahimubc.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 95,
		img: '/babamahimshiri.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 96,
		img: '/babamahimludu.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 97,
		img: '/mayabibabapinkjk.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 98,
		img: '/mayabibababldot.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 99,
		img: '/amramayabiu1.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
	{
		id: 100,
		img: '/amracanada.jpg',
		desc: 'Your fresh perspectives and ideas have the power to shape     	solutions, <b>influence families</b> and drive meaningful change.',
		date: '25.12.2024',
		link: 'See More',
	},
];
