export const items = [
	{
		id: 1,
		title: 'UBC',
		desc: ' get together for birthday party',
		image: '/mahim48.jpg',

		date: '5.6.2022',
	},
	{
		id: 2,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimcar3.JPG',
		date: '5.6.2022',
	},
	{
		id: 3,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimcar2.JPG',
		date: '5.6.2022',
	},

	{
		id: 4,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimwp.JPG',
		date: '5.6.2022',
	},
	{
		id: 5,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimyello.jpg',
		date: '5.6.2022',
	},
	{
		id: 6,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim41.jpg',
		date: '5.6.2022',
	},
	{
		id: 7,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim55.jpg',
		date: '5.6.2022',
	},
	{
		id: 8,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimbaloon.JPG',
		date: '5.6.2022',
	},
	{
		id: 9,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimdadu.JPG',
		date: '5.6.2022',
	},
	{
		id: 10,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimdolna.JPG',
		date: '5.6.2022',
	},
	{
		id: 11,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimgradu.JPG',
		date: '5.6.2022',
	},
	{
		id: 12,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimstatue.JPG',
		date: '5.6.2022',
	},
	{
		id: 13,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimwaki.JPG',
		date: '5.6.2022',
	},
	{
		id: 14,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimarmy.jpg',
		date: '5.6.2022',
	},
	{
		id: 15,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimthai.jpg',
		date: '5.6.2022',
	},
	{
		id: 16,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimwheel.jpg',
		date: '5.6.2022',
	},
	{
		id: 17,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimcoxs.jpg',
		date: '5.6.2022',
	},
	{
		id: 18,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim27.jpg',
		date: '5.6.2022',
	},
	{
		id: 19,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimpurple.jpg',
		date: '5.6.2022',
	},
	{
		id: 20,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimwhitesuite.JPG',
		date: '5.6.2022',
	},
	{
		id: 21,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim51.jpg',
		date: '5.6.2022',
	},
	{
		id: 22,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim49.jpg',
		date: '5.6.2022',
	},
	{
		id: 23,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimflower.jpg',
		date: '5.6.2022',
	},
	{
		id: 24,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimsch.JPG',
		date: '5.6.2022',
	},
	{
		id: 25,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim28.jpg',
		date: '5.6.2022',
	},
	{
		id: 26,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim22.jpg',
		date: '5.6.2022',
	},
	{
		id: 27,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim23.jpg',
		date: '5.6.2022',
	},
	{
		id: 28,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimwall.png',
		date: '5.6.2022',
	},
	{
		id: 29,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim49.jpg',
		date: '5.6.2022',
	},
	{
		id: 30,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimcar5.jpg',
		date: '5.6.2022',
	},
	{
		id: 31,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimcandy.JPG',
		date: '5.6.2022',
	},
	{
		id: 32,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimcom.JPG',
		date: '5.6.2022',
	},
	{
		id: 33,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimsg.png',
		date: '5.6.2022',
	},
	{
		id: 34,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim31.jpg',
		date: '5.6.2022',
	},
	{
		id: 35,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimeidcanada.jpg',
		date: '5.6.2022',
	},
	{
		id: 36,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim32.jpg',
		date: '5.6.2022',
	},
	{
		id: 37,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim66.jpg',
		date: '5.6.2022',
	},
	{
		id: 38,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahim56.jpg',
		date: '5.6.2022',
	},
	{
		id: 39,
		title: 'Blue',
		desc: 'get together for birthday party',
		image: '/mahimjapan.jpg',
		date: '5.6.2022',
	},
];
